FROM node:16.4.2-alpine as build
WORKDIR /app
RUN ls -l
COPY /package.json ./
ADD . ./
RUN npm install --production


FROM nginx:1.21-alpine
COPY ./nginx/default.conf /etc/nginx/conf.d/default.conf
COPY --from=build /app/build /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]