FROM node:16.4.2-alpine as build
RUN curl -fsSL https://get.pnpm.io/install.sh | PNPM_VERSION=7.0.0-rc.3 sh -
WORKDIR /app
ENV PATH /app/node_modules/.bin:$PATH
RUN ls -l
COPY .nvmrc package.json pnpm-lock.yaml ./
RUN pnpm install --frozen-lockfile --prod
ADD . ./
RUN pnpm run build --force


FROM nginx:1.21-alpine
COPY ./nginx/default.conf /etc/nginx/conf.d/default.conf
COPY --from=build /app/build /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]