version: '3'
services:
  pinsel:
    container_name: pinsel
    build:
      context: .
      args:
        - NODE_ENV=production
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=production
    command: node
  nginx:
    image: nginx:1.21-alpine
    ports:
      - '3000:80'
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
