version: '3'
services:
  pinsel:
    container_name: pinsel-dev
    build:
      context: .
      args:
        - NODE_ENV=development
    ports:
      - '3000:3000'
    volumes:
      - ./:/app
      - /app/node_modules
    command: npm run start