FROM node:16.4.2-alpine as build
RUN npm install -g pnpm@next-7
WORKDIR /app
ENV PATH /app/node_modules/.bin:$PATH
COPY /package.json ./
RUN pnpm fetch --prod
ADD . ./
RUN pnpm install -r --offline --prod

FROM nginx:1.21-alpine
COPY nginx/default.conf /etc/nginx/conf.d/default.conf
COPY --from=build /app/build /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]