name: Build / Publish

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-push-docker-image:
    name: Build Pinsel Docker image and push to repos
    runs-on: ubuntu-latest
    steps:
      - name: Checkout codebase
        uses: actions/checkout@v2

      # Setup docker build
      - name: Set up Docker buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secret.DOCKERHUB_TOKEN }}

      - name: Login into Github Packages
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Build image and push it to both registries
        uses: docker/build-push-action@v2
        with:
          context: ../../
          file: ./Dockerfile.prod

          tags: |
            dipet/pinsel-react:$(date +%s)
            ghcr.io/diope/pinsel-react:$(date +%s)
          push: ${{github.ref == 'refs/heads/main'}}

      # - name: Image digest
      #   run: echo ${{ steps.docker_build.outputs.digest }}