name: Build CI/CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-push-docker-image:
    name: Build and Push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout codebase
        uses: actions/checkout@v2
      # - name: Docker meta
      #   id: meta
      #   uses: docker/metadata-action@v3
      #   with:
      #     images: name/app
      #     tags: |
      #       type=ref,event=branch
      #       type=ref,event=pr
      #       type=semver,pattern={{version}}
      #       type=semver,pattern={{major}}.{{minor}}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}
      - name: Build and push to registries
        env:
          CI: false
        uses: docker/build-push-action@v2
        with:
          file: ./Dockerfile.prod
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            dipet/paintbrush:latest
            dipet/paintbrush:1.0.0
            ghcr.io/user/app:latest
            ghcr.io/user/app:1.0.0

      # - name: Image digest
      #   run: echo ${{ steps.docker_build.outputs.digest }}
